services:
  web:
    image: sukjuhong/kwitch-web:latest
    container_name: kwitch-web
    hostname: web
    ports:
      - "8000:8000"
    networks:
      - caddy_proxy

networks:
  caddy_proxy:
    external: true